---
driver:
  name: ec2
  aws_ssh_key_id: gramsay_bot
  region: us-east-1
  security_group_ids: sg-e5bafc83
  subnet_id: subnet-977469ce
  availability_zone: us-east-1a
  instance_type: t1.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for Matt Stratton, Chef"
    created-by: "test-kitchen"
    user: <%= ENV['USER'] %>

verifier:
  name: inspec
  sudo: false
provisioner:
  name: chef_zero
  cookbook_path: C:\Users\Administrator\chef-repo\cookbooks

platforms:
  - name: linux
    driver_config:
      image_id: ami-bf5021d6
    transport:
      username: root
      ssh_key: C:\Users\Administrator\.ssh\gramsay_bot.pem

suites:
  - name: default
    sudo: false
    run_list:
      - recipe[securian-apache::default]
    attributes:
