name 'securian-apache'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures securian-apache'
long_description 'Installs/Configures securian-apache'
version '0.1.0'
